### ISSUE TITLE
System cannot find the path specified

### ISSUE THREAD

**Issue by xd4541** [patientx/ComfyUI-Zluda#24]
### Expected Behavior

Greetings, I have all dependencies. GPU is AMD RX 6600 XT, and i downloaded additional library for it.

### Actual Behavior

cmd says 
`*** Installation is completed in 00:02:42,35 .
*** You can use "start.bat" to start the app later.
.....................................................

*** Starting the Comfyui-ZLUDA for the first time, please be patient...`

And after a while - 
`system cannot find localized path`

### Steps to Reproduce

No response.

### Debug Logs

```powershell
No response.
```

**Comment by patientx** [comment]
where did you install it to ? and maybe post the log if possible.

**Comment by Necc86** [comment]
here's my cmd output from install.bat on a fresh install, all depedencies should be installed and system variables added/checked

```
-------------------------------------------------------------
******************* COMFYUI-ZLUDA INSTALL *******************
-------------------------------------------------------------

 ::  17:22:12  ::  - Setting up the virtual enviroment
 ::  17:22:17  ::  - Virtual enviroment activation
 ::  17:22:17  ::  - Updating the pip package

 ::  17:22:20  ::  Beginning installation ...

 ::  17:22:20  ::  - Installing required packages
 ::  17:23:18  ::  - Installing torch for AMD GPUs (First file is 2.7 GB, please be patient)
 ::  17:24:15  ::  - Installing onnxruntime (required by some nodes)
 ::  17:24:19  ::  - (temporary numpy fix)

 ::  17:24:25  ::  Custom node(s) installation ...

 ::  17:24:25  ::  - Installing Comfyui Manager
 ::  17:24:27  ::  - Installing ComfyUI-deepcache
 ::  17:24:28  ::  - Installing ComfyUI-Impact-Pack

 ::  17:24:31  ::  - Patching ZLUDA (Zluda 3.8.4 for HIP SDK 5.7)
 ::  17:24:38  ::  - ZLUDA is patched.

.....................................................
*** Installation is completed in 00:02:25.97 .
*** You can use "comfyui.bat" to start the app later.
.....................................................

*** Starting the Comfyui-ZLUDA for the first time, please be patient...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-17 17:24:48.054349
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: g:\AI\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: g:\AI\ComfyUI-Zluda
** Log path: g:\AI\ComfyUI-Zluda\comfyui.log

Prestartup times for custom nodes:
   9.3 seconds: G:\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "g:\AI\ComfyUI-Zluda\main.py", line 88, in <module>
    import comfy.utils
  File "g:\AI\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "g:\AI\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "g:\AI\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

```

**Comment by patientx** [comment]
check hip path.

Go into "edit system environment variables."

HIP_PATH C:\Program Files\AMD\ROCm\5.7\bin
HIP_PATH_57 C:\Program Files\AMD\ROCm\5.7\bin
%HIP_PATH%bin C:\Program Files\AMD\ROCm\5.7\bin

In ''user variables for (your pc name)''

Same in "system Variables" but there's an extra step find "Path" in "system Variables" and double click it and It'll open a new interface then click New and add "C:\Program Files\AMD\ROCm\5.7\bin" then click OK to all then restart your pc.

it is on previous issues a few times and I also wrote this in github main readme. Make sure you use hip 5.7 and make sure these path's are on the right places.

**Comment by Necc86** [comment]
Double checked everything, same outcome.
I have a working version of stable-diffusion-webui-directml with zluda, it uses torch 2.2.2 instead of 2.3.0, maybe this info could help.

The build i was able to run can be found here:
`https://forums.guru3d.com/threads/how-to-optimized-automatic1111-zluda-stable-diffusion-webui-on-amd-gpus.451861/`

**Comment by patientx** [comment]
Use figxfor580.bat

**Comment by Necc86** [comment]
I have found a "fixforrx580.bat" which fails to execute, after editing to "@echo on" and running from the command prompt, it stops after this line: "venv\scripts\activate" and it gives me a prompt starting with (venv) .

Manually copy-pasting the rest of the code to the command prompt works, i could confirm that torch was downgraded to 2.2.1 but the error message is the same.

**Comment by patientx** [comment]
change the zluda address with this :
https://github.com/lshqqytiger/ZLUDA/releases/download/rel.4f12e8cfe9fa53bd29637c0bfe6fc88494d2b10f/ZLUDA-windows-amd64.zip
old version , maybe this new one caused some problems but I don't think so, others seem to be able to install without any problems , only you and the other issue op.
