### ISSUE TITLE
caffe2_nvrtc.dll error with a non windows store python

### ISSUE THREAD

**Issue by Nevaehni** [patientx/ComfyUI-Zluda#30]
### Expected Behavior

The webui to start running

### Actual Behavior

Fails and gives me an error

### Steps to Reproduce

Starting install.bat gives me this after starting the webui.
Starting comfyui.bat also returns the same.

### Debug Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2024-10-16 15:28] ** ComfyUI startup time: 2024-10-16 15:28:43.278157
[2024-10-16 15:28] ** Platform: Windows
[2024-10-16 15:28] ** Python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
[2024-10-16 15:28] ** Python executable: C:\Users\Admin\Downloads\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-10-16 15:28] ** ComfyUI Path: C:\Users\Admin\Downloads\ComfyUI-Zluda
[2024-10-16 15:28] ** Log path: C:\Users\Admin\Downloads\ComfyUI-Zluda\comfyui.log
[2024-10-16 15:28] 
Prestartup times for custom nodes:
[2024-10-16 15:28]    1.8 seconds: C:\Users\Admin\Downloads\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-10-16 15:28] 
Traceback (most recent call last):
[2024-10-16 15:28]   File "C:\Users\Admin\Downloads\ComfyUI-Zluda\main.py", line 88, in <module>
[2024-10-16 15:28]     import comfy.utils
[2024-10-16 15:28]   File "C:\Users\Admin\Downloads\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
[2024-10-16 15:28]     import torch
[2024-10-16 15:28]   File "C:\Users\Admin\Downloads\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 141, in <module>
[2024-10-16 15:28]     raise err
[2024-10-16 15:28] OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Admin\Downloads\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

### Other

I've removed python with bulk crap remover, restarted and reinstalled again. I do not have python installed via windows store. My Python version is 3.11. The file C:\Users\Admin\Downloads\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll does exists.

**Comment by Foxtrot47** [comment]
Try adding a new entry to PATH system environment variable `C:\Program Files\AMD\ROCm\5.7\bin`

**Comment by F1zzyD** [comment]
I have this issue as well. Following the steps exactly and looking at the troubleshooting at the bottom of the guide still gives "caffe2_nvrtc.dll" errors.

**Comment by Nevaehni** [comment]
It is already in my PATH in system and user environments. I'm closing this thread because i'm not using it anymore, not because it is fixed.

**Comment by rwfsmith** [comment]
I fixed this issue by adding my zluda folder to the path, it seems like.
