### ISSUE TITLE
Out of memory? RX580 

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [patientx/ComfyUI-Zluda#32]
### Expected Behavior

Default Workflow generation

### Actual Behavior

![image](https://github.com/user-attachments/assets/96
I don't know I'm running out of memory :(
![image](https://github.com/user-attachments/assets/c2a67bd5-5ac8-4e8f-ab1d-a34697cfd421)
7cc01c-e120-4f04-8dbd-168e0a341a5f)

### Steps to Reproduce

Usual installation without any custom node or with custom node

### Debug Logs

```powershell
Traceback (most recent call last):
  File "E:\Luda\ComfyUI-Zluda\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Luda\ComfyUI-Zluda\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Luda\ComfyUI-Zluda\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Luda\ComfyUI-Zluda\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Luda\ComfyUI-Zluda\nodes.py", line 1437, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "E:\Luda\ComfyUI-Zluda\nodes.py", line 1404, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\Luda\ComfyUI-Zluda\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\Luda\ComfyUI-Zluda\comfy\samplers.py", line 832, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\Luda\ComfyUI-Zluda\comfy\samplers.py", line 732, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "E:\Luda\ComfyUI-Zluda\comfy\samplers.py", line 719, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "E:\Luda\ComfyUI-Zluda\comfy\samplers.py", line 691, in inner_sample
    if latent_image is not None and torch.count_nonzero(latent_image) > 0: #Don't shift the empty latent image.
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 4.90 seconds
fatal: No names found, cannot describe anything.
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```

**Comment by patientx** [comment]
First of all run the "https://github.com/patientx/ComfyUI-Zluda/blob/master/fixforrx580.bat" , these old torch version runs better with rx580/480. 
Second try to run the app without any other stuff running the background , no video play etc. Best would be to just open comfy after booting and using it with a browser without any other tabs open.

**Comment by login0false** [comment]
> First of all run the "https://github.com/patientx/ComfyUI-Zluda/blob/master/fixforrx580.bat" , these old torch version runs better with rx580/480. 
I think this should be in installation instructions for more clarity.

**Comment by patientx** [comment]
> > First of all run the "https://github.com/patientx/ComfyUI-Zluda/blob/master/fixforrx580.bat" , these old torch version runs better with rx580/480.
> 
> I feel this should be in installation instructions for more clarity. Maybe also mention lower-tier cards somehow, and this applies to them too (at least to my rx570).

thanks for the suggestion, I thought this was mentioned on troubleshooting part and maybe it was there once but got deleted with some previous update. Now I added it as a warning.
