### ISSUE TITLE
Memory Overload with flux GGUF

### ISSUE THREAD

**Issue by GoudaCouda** [patientx/ComfyUI-Zluda#38]
### Your question

I am trying to run a flux gguf I have tried both q4 and q2 and it is not working.I have 12gb of vram and 40gb of ram.

### Logs

```powershell
5:56:37.001 [Warning] Your system memory usage exceeded 98.2% just before the backend process failed. This might indicate a memory overload.
15:56:37.002 [Warning] You appear to have a sufficient pagefile (88.1 GiB), so you might have too many background processes, or you might just be trying to run too much.
15:56:37.002 [Warning] Consider closing background processes, or greatly expanding your pagefile size.
15:56:37.003 [Warning] Or, reduce the size of what you're trying to run. If you're running an FP16 or FP8 model, consider a quantized variant like GGUF Q4.
15:56:37.004 [Warning]
```

**Comment by GoudaCouda** [comment]
Here is the log and comfy work flow its just a basic flux gguf
![image](https://github.com/user-attachments/assets/94489b66-6ad1-4084-8a51-a2aeb92d0e48)



## ComfyUI-Manager: installing dependencies done.
[2024-11-06 18:30:34.210] ** ComfyUI startup time: 2024-11-06 18:30:34.210695
[2024-11-06 18:30:34.302] ** Platform: Windows
[2024-11-06 18:30:34.303] ** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
[2024-11-06 18:30:34.303] ** Python executable: C:\Users\austi\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-11-06 18:30:34.303] ** ComfyUI Path: C:\Users\austi\ComfyUI-Zluda
[2024-11-06 18:30:34.303] ** Log path: C:\Users\austi\ComfyUI-Zluda\comfyui.log
[2024-11-06 18:30:34.309] 
Prestartup times for custom nodes:
[2024-11-06 18:30:34.309]    1.7 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-11-06 18:30:34.310] 
Total VRAM 12272 MB, total RAM 40886 MB
[2024-11-06 18:30:36.002] pytorch version: 2.3.0+cu118
[2024-11-06 18:30:36.002] Set vram state to: NORMAL_VRAM
[2024-11-06 18:30:36.002]  
[2024-11-06 18:30:36.002] ***----------------------ZLUDA--------------------------***
[2024-11-06 18:30:36.003]   ::  ZLUDA detected, disabling non-supported functions.
[2024-11-06 18:30:36.003]   ::  (cuDNN, flash_sdp, mem_efficient_sdp disabled) 
[2024-11-06 18:30:36.003] ***-----------------------------------------------------***
[2024-11-06 18:30:36.003]   ::  Device: cuda:0 AMD Radeon RX 6700 XT [ZLUDA] : native
[2024-11-06 18:30:36.003]  
[2024-11-06 18:30:37.361] Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[2024-11-06 18:30:38.115] [Prompt Server] web root: C:\Users\austi\ComfyUI-Zluda\web
[2024-11-06 18:30:38.568] ### Loading: ComfyUI-Impact-Pack (V7.10.7)
[2024-11-06 18:30:38.571] [Impact Pack] Failed to import due to several dependencies are missing!!!!
[2024-11-06 18:30:38.572] Traceback (most recent call last):
  File "C:\Users\austi\ComfyUI-Zluda\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 53, in <module>
    raise e
  File "C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 31, in <module>
    import impact.subpack_nodes  # This import must be done before cv2.
  File "C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 3, in <module>
    import impact.core as core
  File "C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 7, in <module>
    from segment_anything import SamPredictor
ModuleNotFoundError: No module named 'segment_anything'

[2024-11-06 18:30:38.572] Cannot import C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'segment_anything'
[2024-11-06 18:30:38.575] ### Loading: ComfyUI-Manager (V2.51.9)
[2024-11-06 18:30:38.902] ### ComfyUI Revision: 3000 [79efdb2f] | Released on '2024-11-06'
[2024-11-06 18:30:39.072] 
Import times for custom nodes:
[2024-11-06 18:30:39.072]    0.0 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
[2024-11-06 18:30:39.073]    0.0 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
[2024-11-06 18:30:39.073]    0.0 seconds (IMPORT FAILED): C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack
[2024-11-06 18:30:39.073]    0.0 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF
[2024-11-06 18:30:39.073]    0.5 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-11-06 18:30:39.073] 
[2024-11-06 18:30:39.079] Starting server

[2024-11-06 18:30:39.079] To see the GUI go to: http://127.0.0.1:8188
[2024-11-06 18:30:39.158] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-11-06 18:30:39.164] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-11-06 18:30:39.174] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-11-06 18:30:39.220] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-11-06 18:30:39.238] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-11-06 18:30:39.737] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2024-11-06 18:30:58.477] got prompt
[2024-11-06 18:30:58.479] Failed to validate prompt for output 9:
[2024-11-06 18:30:58.481] * VAELoader 10:
[2024-11-06 18:30:58.481]   - Value not in list: vae_name: 'ae.safetensors' not in ['Flux\\ae.safetensors']
[2024-11-06 18:30:58.481] Output will be ignored
[2024-11-06 18:30:58.482] invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
[2024-11-06 18:31:02.515] got prompt
[2024-11-06 18:31:02.555] Using split attention in VAE
[2024-11-06 18:31:02.557] Using split attention in VAE
[2024-11-06 18:31:02.772] C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF\nodes.py:79: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:212.)
  torch_tensor = torch.from_numpy(tensor.data) # mmap
[2024-11-06 18:31:02.778] 
ggml_sd_loader:
[2024-11-06 18:31:02.779]  GGMLQuantizationType.F32      471
[2024-11-06 18:31:02.779]  GGMLQuantizationType.Q3_K     304
[2024-11-06 18:31:02.780]  GGMLQuantizationType.F16        5
[2024-11-06 18:31:02.804] model weight dtype torch.float16, manual cast: None
[2024-11-06 18:31:02.814] model_type FLUX
[2024-11-06 18:31:03.198] clip missing: ['text_projection.weight']
[2024-11-06 18:31:12.504] Requested to load SD3ClipModel_
[2024-11-06 18:31:12.505] Loading 1 new model
[2024-11-06 18:31:14.987] loaded completely 0.0 4777.53759765625 True

**Comment by GoudaCouda** [comment]
It just gets to the model loaded and then just disconnects

**Comment by patientx** [comment]
You seem to have other problems first, install that missing package and also change type to "flux" on dual clip loader. 
To make it clean, uninstall impact pack , close and restart comfy. Reinstall from manager and close and restart. 

I have an rx 6600 (8 gb vram) and with that I am able to run for example q4 gguf (on even fp8 version of dev or schnell in safetensors format which is around 11gb) easily with your workflow without any problems. I have now 32 gb system ram but I was also able to run it with 16 gb system ram.

**Comment by GoudaCouda** [comment]
Yea sorry that was an older screen shot I I fixed the clip loader and I uninstalled impact pack. And still the same thing here are the logs It just logs the model and then stops.When I use it as a backend on SwarmUI it does the same thing but gives me a Memory Overload Error message which I can post as well. I have a 6700xt with 40gb of ram.

## ComfyUI-Manager: installing dependencies done.
[2024-11-07 09:53:40.962] ** ComfyUI startup time: 2024-11-07 09:53:40.962041
[2024-11-07 09:53:41.056] ** Platform: Windows
[2024-11-07 09:53:41.057] ** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
[2024-11-07 09:53:41.057] ** Python executable: C:\Users\austi\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-11-07 09:53:41.057] ** ComfyUI Path: C:\Users\austi\ComfyUI-Zluda
[2024-11-07 09:53:41.057] ** Log path: C:\Users\austi\ComfyUI-Zluda\comfyui.log
[2024-11-07 09:53:41.063] 
Prestartup times for custom nodes:
[2024-11-07 09:53:41.064]    1.9 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-11-07 09:53:41.064] 
Total VRAM 12272 MB, total RAM 40886 MB
[2024-11-07 09:53:42.753] pytorch version: 2.3.0+cu118
[2024-11-07 09:53:42.754] Set vram state to: NORMAL_VRAM
[2024-11-07 09:53:42.754]  
[2024-11-07 09:53:42.754] ***----------------------ZLUDA--------------------------***
[2024-11-07 09:53:42.754]   ::  ZLUDA detected, disabling non-supported functions.
[2024-11-07 09:53:42.754]   ::  (cuDNN, flash_sdp, mem_efficient_sdp disabled) 
[2024-11-07 09:53:42.754] ***-----------------------------------------------------***
[2024-11-07 09:53:42.754]   ::  Device: cuda:0 AMD Radeon RX 6700 XT [ZLUDA] : native
[2024-11-07 09:53:42.754]  
[2024-11-07 09:53:44.103] Using split optimization for cross attention
[2024-11-07 09:53:44.853] [Prompt Server] web root: C:\Users\austi\ComfyUI-Zluda\web
[2024-11-07 09:53:45.306] ### Loading: ComfyUI-Manager (V2.51.9)
[2024-11-07 09:53:45.766] ### ComfyUI Revision: 3003 [0a026227] | Released on '2024-11-07'
[2024-11-07 09:53:45.946] 
Import times for custom nodes:
[2024-11-07 09:53:45.946]    0.0 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
[2024-11-07 09:53:45.946]    0.0 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
[2024-11-07 09:53:45.946]    0.0 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF
[2024-11-07 09:53:45.947]    0.6 seconds: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-11-07 09:53:45.947] 
[2024-11-07 09:53:45.952] Starting server

[2024-11-07 09:53:45.952] To see the GUI go to: http://127.0.0.1:8188
[2024-11-07 09:53:46.061] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-11-07 09:53:46.067] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-11-07 09:53:46.089] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-11-07 09:53:46.123] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-11-07 09:53:46.144] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-11-07 09:53:46.595] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2024-11-07 09:53:57.430] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
[2024-11-07 09:53:57.455] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
[2024-11-07 09:53:57.631] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
[2024-11-07 09:53:57.751] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
[2024-11-07 09:54:01.346] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
[2024-11-07 09:54:01.364] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
[2024-11-07 09:54:01.368] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
[2024-11-07 09:54:01.370] Start update check...[2K
Update check done.
[2024-11-07 09:54:02.987] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
[2024-11-07 09:54:03.003] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
[2024-11-07 09:54:03.007] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
[2024-11-07 09:54:03.113] FETCH DATA from: C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
[2024-11-07 09:54:47.507] got prompt
[2024-11-07 09:54:47.551] Using split attention in VAE
[2024-11-07 09:54:47.553] Using split attention in VAE
[2024-11-07 09:54:48.526] C:\Users\austi\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF\nodes.py:79: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:212.)
  torch_tensor = torch.from_numpy(tensor.data) # mmap
[2024-11-07 09:54:48.534] 
ggml_sd_loader:
[2024-11-07 09:54:48.535]  GGMLQuantizationType.F32      471
[2024-11-07 09:54:48.535]  GGMLQuantizationType.Q3_K     304
[2024-11-07 09:54:48.535]  GGMLQuantizationType.F16        5
[2024-11-07 09:54:48.564] model weight dtype torch.float16, manual cast: None
[2024-11-07 09:54:48.572] model_type FLUX
[2024-11-07 09:54:49.345] clip missing: ['text_projection.weight']
[2024-11-07 09:54:58.477] Requested to load FluxClipModel_
[2024-11-07 09:54:58.480] Loading 1 new model
[2024-11-07 09:55:00.778] loaded completely 0.0 4777.53759765625 True


Swarm Ui cancels at the same point but also gives this


2024-11-07 10:02:00.362 [Warning] 

2024-11-07 10:02:00.363 [Warning] Your system memory usage exceeded 98.2% just before the backend process failed. This might indicate a memory overload.
2024-11-07 10:02:00.363 [Warning] You appear to have a sufficient pagefile (88.1 GiB), so you might have too many background processes, or you might just be trying to run too much.
2024-11-07 10:02:00.364 [Warning] Consider closing background processes, or greatly expanding your pagefile size.
2024-11-07 10:02:00.365 [Warning] Or, reduce the size of what you're trying to run. If you're running an FP16 or FP8 model, consider a quantized variant like GGUF Q4.
2024-11-07 10:02:00.367 [Warning]
